### ISSUE TITLE
openresty folder moved

### ISSUE THREAD

**Issue by Tieske** [Kong/homebrew-kong#169]
```shell
$ which luajit
/usr/local/opt/openresty/openresty/luajit/bin/luajit
```

Notice the double `openresty` in the path. Previously this was singular. Seems like an unintended change.

**Comment by kikito** [comment]
Thanks for reporting. I added this to our board.

**Comment by gszr** [comment]
Thanks for reporting, @Tieske!

This is expected and traces back to the [1.3.0 bump](https://github.com/Kong/homebrew-kong/commit/98c1356f74bab0b435b86da97d6e2f314835d541)

Before that bump, this formula built OpenResty manually, not using kong-built-tools. As such, OpenSSL and LuaRocks had their own formulas. 

As kong-build-tools handles the logic for building OpenSSL and LuaRocks, these now live under the OpenResty formula prefix (by default `/usr/local/opt/openresty`). So, `/usr/local/opt/openresty` is the path to the `openresty` formula's assets (which includes dependencies), not to openresty only.

(If we somehow managed to change the default prefix for the `openresty` formula (which I am not sure homebrew allows), `luarocks` and `openssl` would pollute Brew's prefix `/usr/local/opt` -- which is bad, as that could lead to conflicts with other formulas.)

Given that this doesn't affect the formula's functioning (it's a cosmetic issue), I would call this expected behavior and a "won't fix".

**Comment by Tieske** [comment]
as long as we agree, I'm fine with it.

**Comment by kikito** [comment]
Ok, I'm closing this one down then.
